### ISSUE TITLE
Pie Gsi and Los 16

### ISSUE THREAD

**Issue by shimabde** [gloeyisk/UniversalGMSDoze#1]
Still won't push gms to optimized options

**Comment by xerta555** [comment]
> Still won't push gms to optimized options

Hello, all magisk module have the same issue on Pie, for my two magisk module:
https://forum.xda-developers.com/apps/magisk/module-exsdcard-write-access-enabler-t3670428/post73727554
https://forum.xda-developers.com/apps/magisk/module-cloudfaredns4magisk-t3772375/
there are some issue only for Pie users (Android 9).

Also, it's just useless to report an unknow issue like "don't work" without any logfiles/dsmeg/logcat files. U should report your issue with all informations on the Magisk git.

**Comment by shimabde** [comment]
Oh okay,hope seeing this tweak working someday sir

**Comment by xerta555** [comment]
@shimabde i would like too but it's seems to be too hard.
Xposed framework is always in beta stage for Oreo and rovo taked 1 year to port it on Nougat so.....
