### ISSUE TITLE
How can I provide u logs? Step to go through? Which files? I want to help by sending it. 

### ISSUE THREAD

**Issue by PranavBhattrai** [gloeyisk/UniversalGMSDoze#3]

**Comment by HafizZiq** [comment]
> _No description provided._

Can you state ur issue?

**Comment by HafizZiq** [comment]
@HafizZiq Dun quote meh

**Comment by HafizZiq** [comment]
@HafizZiq Pff

**Comment by gloeyisk** [comment]
> _No description provided._

Thanks for your participation. There's no log file for this module, you can record a log from 3rd apps or simply sending me default sysconfig files (`/system/etc/sysconfig`). I'll close this issue and check everything else after I've done about all of my privacy stuff.

**Comment by PranavBhattrai** [comment]
> > _No description provided._
> 
> Can you state ur issue?

i wanted to make sure this works on Oneplus 5. So i offered to help. 
Apperently, there is no "log" system for this. 
Hope it properly works in my device. 
Is there a way to know whether this working perfectly fine?
