### ISSUE TITLE
I have installed, rebooted and went to "running services" in Developers Option to see if anything is in effect. 

### ISSUE THREAD

**Issue by PranavBhattari** [gloeyisk/UniversalGMSDoze#4]
But unfortunately it's not.

Screenshot available:
![Screenshot_20190507-205858](https://user-images.githubusercontent.com/32763112/57311530-58b64600-70db-11e9-9979-ac38c12aa1d7.jpg)
![Screenshot_20190507-205934](https://user-images.githubusercontent.com/32763112/57311567-67046200-70db-11e9-8cef-51db20dbbc13.jpg)

**Comment by gloeyisk** [comment]
It's doesn't mean GMS will stopped 100%, if you want like that then you should prepare for some troubles. Visit the support group so we can talking there. I mostly active in Telegram (hopefully).
Closed this issue.
